/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 56
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 1
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_COMMA = 2,
  sym_int_literal = 3,
  sym_float_literal = 4,
  sym_bool_literal = 5,
  anon_sym_SQUOTE = 6,
  aux_sym_char_literal_token1 = 7,
  anon_sym_DQUOTE = 8,
  aux_sym_string_literal_token1 = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_EQ = 12,
  anon_sym_LBRACK = 13,
  anon_sym_RBRACK = 14,
  anon_sym_COLON = 15,
  anon_sym_Float = 16,
  anon_sym_bool = 17,
  anon_sym__ = 18,
  sym_any_type = 19,
  anon_sym_new = 20,
  anon_sym_static = 21,
  anon_sym_public = 22,
  anon_sym_stock = 23,
  anon_sym_const = 24,
  sym_escape_sequence = 25,
  anon_sym_SEMI = 26,
  sym_source_file = 27,
  sym__definition = 28,
  sym_global_variable_declaration = 29,
  sym_variable = 30,
  sym__expression = 31,
  sym__literal = 32,
  sym_char_literal = 33,
  sym_string_literal = 34,
  sym_array_literal = 35,
  sym__value = 36,
  sym_dimension = 37,
  sym__type_definition = 38,
  sym__type = 39,
  sym_builtin_type = 40,
  sym_global_variable_modifiers = 41,
  sym__semicolon = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_global_variable_declaration_repeat1 = 44,
  aux_sym_variable_repeat1 = 45,
  aux_sym_string_literal_repeat1 = 46,
  aux_sym_array_literal_repeat1 = 47,
  aux_sym_global_variable_modifiers_repeat1 = 48,
  alias_sym_string_content = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_COMMA] = ",",
  [sym_int_literal] = "int_literal",
  [sym_float_literal] = "float_literal",
  [sym_bool_literal] = "bool_literal",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_char_literal_token1] = "character",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_Float] = "Float",
  [anon_sym_bool] = "bool",
  [anon_sym__] = "_",
  [sym_any_type] = "any_type",
  [anon_sym_new] = "new",
  [anon_sym_static] = "static",
  [anon_sym_public] = "public",
  [anon_sym_stock] = "stock",
  [anon_sym_const] = "const",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_global_variable_declaration] = "global_variable_declaration",
  [sym_variable] = "variable",
  [sym__expression] = "_expression",
  [sym__literal] = "_literal",
  [sym_char_literal] = "char_literal",
  [sym_string_literal] = "string_literal",
  [sym_array_literal] = "array_literal",
  [sym__value] = "_value",
  [sym_dimension] = "dimension",
  [sym__type_definition] = "_type_definition",
  [sym__type] = "_type",
  [sym_builtin_type] = "builtin_type",
  [sym_global_variable_modifiers] = "modifiers",
  [sym__semicolon] = "_semicolon",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_global_variable_declaration_repeat1] = "global_variable_declaration_repeat1",
  [aux_sym_variable_repeat1] = "variable_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_array_literal_repeat1] = "array_literal_repeat1",
  [aux_sym_global_variable_modifiers_repeat1] = "global_variable_modifiers_repeat1",
  [alias_sym_string_content] = "string_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_int_literal] = sym_int_literal,
  [sym_float_literal] = sym_float_literal,
  [sym_bool_literal] = sym_bool_literal,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_char_literal_token1] = aux_sym_char_literal_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_Float] = anon_sym_Float,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym__] = anon_sym__,
  [sym_any_type] = sym_any_type,
  [anon_sym_new] = anon_sym_new,
  [anon_sym_static] = anon_sym_static,
  [anon_sym_public] = anon_sym_public,
  [anon_sym_stock] = anon_sym_stock,
  [anon_sym_const] = anon_sym_const,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_global_variable_declaration] = sym_global_variable_declaration,
  [sym_variable] = sym_variable,
  [sym__expression] = sym__expression,
  [sym__literal] = sym__literal,
  [sym_char_literal] = sym_char_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_array_literal] = sym_array_literal,
  [sym__value] = sym__value,
  [sym_dimension] = sym_dimension,
  [sym__type_definition] = sym__type_definition,
  [sym__type] = sym__type,
  [sym_builtin_type] = sym_builtin_type,
  [sym_global_variable_modifiers] = sym_global_variable_modifiers,
  [sym__semicolon] = sym__semicolon,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_global_variable_declaration_repeat1] = aux_sym_global_variable_declaration_repeat1,
  [aux_sym_variable_repeat1] = aux_sym_variable_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_array_literal_repeat1] = aux_sym_array_literal_repeat1,
  [aux_sym_global_variable_modifiers_repeat1] = aux_sym_global_variable_modifiers_repeat1,
  [alias_sym_string_content] = alias_sym_string_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_int_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_char_literal_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym_any_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_new] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_static] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_public] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stock] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_global_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_dimension] = {
    .visible = true,
    .named = true,
  },
  [sym__type_definition] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_builtin_type] = {
    .visible = true,
    .named = true,
  },
  [sym_global_variable_modifiers] = {
    .visible = true,
    .named = true,
  },
  [sym__semicolon] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_global_variable_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_global_variable_modifiers_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_string_content] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_size = 2,
  field_type = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_size] = "size",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 3},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_value, 1, .inherited = true},
  [3] =
    {field_name, 1},
    {field_type, 0, .inherited = true},
  [5] =
    {field_type, 0},
  [6] =
    {field_value, 1},
  [7] =
    {field_name, 0},
    {field_value, 2, .inherited = true},
  [9] =
    {field_name, 1},
    {field_type, 0, .inherited = true},
    {field_value, 2, .inherited = true},
  [12] =
    {field_size, 1},
  [13] =
    {field_name, 1},
    {field_type, 0, .inherited = true},
    {field_value, 3, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [10] = {
    [1] = alias_sym_string_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_string_literal_repeat1, 2,
    aux_sym_string_literal_repeat1,
    alias_sym_string_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
};

static const TSCharacterRange sym_escape_sequence_character_set_1[] = {
  {'"', '"'}, {'%', '%'}, {'\'', '\''}, {'0', '9'}, {'\\', '\\'}, {'a', 'b'}, {'e', 'f'}, {'n', 'n'},
  {'r', 'r'}, {'t', 't'}, {'x', 'x'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '"', 23,
        '\'', 19,
        ',', 11,
        '0', 12,
        ':', 30,
        ';', 37,
        '=', 27,
        '[', 28,
        '\\', 6,
        ']', 29,
        '{', 25,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'x') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (set_contains(sym_escape_sequence_character_set_1, 11, lookahead)) ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(5);
      if (lookahead == '\\') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == 'x') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (set_contains(sym_escape_sequence_character_set_1, 11, lookahead)) ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(14);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == 'b') ADVANCE(7);
      if (lookahead == 'x') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_int_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == '-') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == 'e') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_char_literal_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_char_literal_token1);
      if (lookahead == '\\') ADVANCE(6);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_char_literal_token1);
      if (lookahead == 'x') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (set_contains(sym_escape_sequence_character_set_1, 11, lookahead)) ADVANCE(32);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (lookahead == ';') ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'F', 1,
        '_', 2,
        'a', 3,
        'b', 4,
        'c', 5,
        'f', 6,
        'n', 7,
        'p', 8,
        's', 9,
        't', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'y') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'w') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'b') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(27);
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_any_type);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_new);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 28:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 36:
      if (lookahead == 'k') ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_bool_literal);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_Float);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(43);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_stock);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_public);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_static);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_int_literal] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [sym_bool_literal] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_Float] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym_any_type] = ACTIONS(1),
    [anon_sym_new] = ACTIONS(1),
    [anon_sym_static] = ACTIONS(1),
    [anon_sym_public] = ACTIONS(1),
    [anon_sym_stock] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(53),
    [sym__definition] = STATE(10),
    [sym_global_variable_declaration] = STATE(10),
    [sym_global_variable_modifiers] = STATE(28),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_global_variable_modifiers_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_new] = ACTIONS(5),
    [anon_sym_static] = ACTIONS(5),
    [anon_sym_public] = ACTIONS(5),
    [anon_sym_stock] = ACTIONS(5),
    [anon_sym_const] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_COLON,
    STATE(34), 1,
      sym__value,
    STATE(3), 2,
      sym_dimension,
      aux_sym_variable_repeat1,
    ACTIONS(7), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [27] = 5,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(31), 1,
      sym__value,
    STATE(9), 2,
      sym_dimension,
      aux_sym_variable_repeat1,
    ACTIONS(15), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [51] = 7,
    ACTIONS(19), 1,
      sym_float_literal,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    ACTIONS(17), 3,
      sym_int_literal,
      sym_bool_literal,
      sym_identifier,
    STATE(55), 5,
      sym__expression,
      sym__literal,
      sym_char_literal,
      sym_string_literal,
      sym_array_literal,
  [79] = 5,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(32), 1,
      sym__value,
    STATE(6), 2,
      sym_dimension,
      aux_sym_variable_repeat1,
    ACTIONS(29), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [103] = 5,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(33), 1,
      sym__value,
    STATE(9), 2,
      sym_dimension,
      aux_sym_variable_repeat1,
    ACTIONS(31), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [127] = 6,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      sym_float_literal,
    ACTIONS(33), 3,
      sym_int_literal,
      sym_bool_literal,
      sym_identifier,
    STATE(35), 5,
      sym__expression,
      sym__literal,
      sym_char_literal,
      sym_string_literal,
      sym_array_literal,
  [152] = 8,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      anon_sym_COMMA,
    ACTIONS(39), 1,
      sym_int_literal,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(41), 2,
      sym_float_literal,
      sym_bool_literal,
    STATE(43), 4,
      sym__literal,
      sym_char_literal,
      sym_string_literal,
      sym_array_literal,
  [181] = 3,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    STATE(9), 2,
      sym_dimension,
      aux_sym_variable_repeat1,
    ACTIONS(45), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [200] = 5,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      aux_sym_global_variable_modifiers_repeat1,
    STATE(28), 1,
      sym_global_variable_modifiers,
    STATE(13), 3,
      sym__definition,
      sym_global_variable_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(5), 5,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
  [222] = 3,
    STATE(12), 1,
      aux_sym_global_variable_modifiers_repeat1,
    ACTIONS(52), 5,
      anon_sym_Float,
      anon_sym_bool,
      anon_sym__,
      sym_any_type,
      sym_identifier,
    ACTIONS(54), 5,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
  [240] = 3,
    STATE(12), 1,
      aux_sym_global_variable_modifiers_repeat1,
    ACTIONS(56), 5,
      anon_sym_Float,
      anon_sym_bool,
      anon_sym__,
      sym_any_type,
      sym_identifier,
    ACTIONS(58), 5,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
  [258] = 5,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      aux_sym_global_variable_modifiers_repeat1,
    STATE(28), 1,
      sym_global_variable_modifiers,
    STATE(13), 3,
      sym__definition,
      sym_global_variable_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(63), 5,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
  [280] = 7,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(66), 1,
      sym_int_literal,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    ACTIONS(68), 2,
      sym_float_literal,
      sym_bool_literal,
    STATE(47), 4,
      sym__literal,
      sym_char_literal,
      sym_string_literal,
      sym_array_literal,
  [306] = 7,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(66), 1,
      sym_int_literal,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    ACTIONS(68), 2,
      sym_float_literal,
      sym_bool_literal,
    STATE(47), 4,
      sym__literal,
      sym_char_literal,
      sym_string_literal,
      sym_array_literal,
  [332] = 5,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(78), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      aux_sym_global_variable_declaration_repeat1,
    STATE(37), 1,
      sym__semicolon,
    ACTIONS(74), 6,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
  [353] = 5,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(82), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      aux_sym_global_variable_declaration_repeat1,
    STATE(38), 1,
      sym__semicolon,
    ACTIONS(80), 6,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
  [374] = 1,
    ACTIONS(84), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [387] = 1,
    ACTIONS(86), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [400] = 1,
    ACTIONS(88), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [413] = 1,
    ACTIONS(90), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [426] = 1,
    ACTIONS(92), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [439] = 1,
    ACTIONS(94), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [452] = 1,
    ACTIONS(96), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [465] = 1,
    ACTIONS(98), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [478] = 1,
    ACTIONS(100), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [491] = 6,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(66), 1,
      sym_int_literal,
    ACTIONS(68), 2,
      sym_float_literal,
      sym_bool_literal,
    STATE(47), 4,
      sym__literal,
      sym_char_literal,
      sym_string_literal,
      sym_array_literal,
  [514] = 6,
    ACTIONS(102), 1,
      sym_identifier,
    ACTIONS(106), 1,
      sym_any_type,
    STATE(16), 1,
      sym_variable,
    STATE(48), 1,
      sym__type_definition,
    STATE(50), 2,
      sym__type,
      sym_builtin_type,
    ACTIONS(104), 3,
      anon_sym_Float,
      anon_sym_bool,
      anon_sym__,
  [536] = 6,
    ACTIONS(102), 1,
      sym_identifier,
    ACTIONS(106), 1,
      sym_any_type,
    STATE(36), 1,
      sym_variable,
    STATE(48), 1,
      sym__type_definition,
    STATE(50), 2,
      sym__type,
      sym_builtin_type,
    ACTIONS(104), 3,
      anon_sym_Float,
      anon_sym_bool,
      anon_sym__,
  [558] = 3,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_global_variable_declaration_repeat1,
    ACTIONS(108), 7,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [574] = 1,
    ACTIONS(113), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [585] = 1,
    ACTIONS(115), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [596] = 1,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [607] = 1,
    ACTIONS(119), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [618] = 1,
    ACTIONS(121), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [629] = 1,
    ACTIONS(108), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
      anon_sym_SEMI,
  [640] = 1,
    ACTIONS(80), 6,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
  [649] = 1,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_static,
      anon_sym_public,
      anon_sym_stock,
      anon_sym_const,
  [658] = 4,
    ACTIONS(125), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      aux_sym_string_literal_token1,
    ACTIONS(129), 1,
      sym_escape_sequence,
    STATE(41), 1,
      aux_sym_string_literal_repeat1,
  [671] = 4,
    ACTIONS(127), 1,
      aux_sym_string_literal_token1,
    ACTIONS(129), 1,
      sym_escape_sequence,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      aux_sym_string_literal_repeat1,
  [684] = 4,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      aux_sym_string_literal_token1,
    ACTIONS(138), 1,
      sym_escape_sequence,
    STATE(41), 1,
      aux_sym_string_literal_repeat1,
  [697] = 2,
    ACTIONS(143), 1,
      aux_sym_string_literal_token1,
    ACTIONS(141), 2,
      anon_sym_DQUOTE,
      sym_escape_sequence,
  [705] = 3,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      aux_sym_array_literal_repeat1,
  [715] = 3,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_array_literal_repeat1,
  [725] = 3,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      aux_sym_array_literal_repeat1,
  [735] = 1,
    ACTIONS(156), 2,
      aux_sym_char_literal_token1,
      sym_escape_sequence,
  [740] = 1,
    ACTIONS(154), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [745] = 1,
    ACTIONS(158), 1,
      sym_identifier,
  [749] = 1,
    ACTIONS(160), 1,
      anon_sym_SQUOTE,
  [753] = 1,
    ACTIONS(162), 1,
      anon_sym_COLON,
  [757] = 1,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
  [761] = 1,
    ACTIONS(164), 1,
      sym_identifier,
  [765] = 1,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
  [769] = 1,
    ACTIONS(168), 1,
      anon_sym_COLON,
  [773] = 1,
    ACTIONS(170), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 51,
  [SMALL_STATE(5)] = 79,
  [SMALL_STATE(6)] = 103,
  [SMALL_STATE(7)] = 127,
  [SMALL_STATE(8)] = 152,
  [SMALL_STATE(9)] = 181,
  [SMALL_STATE(10)] = 200,
  [SMALL_STATE(11)] = 222,
  [SMALL_STATE(12)] = 240,
  [SMALL_STATE(13)] = 258,
  [SMALL_STATE(14)] = 280,
  [SMALL_STATE(15)] = 306,
  [SMALL_STATE(16)] = 332,
  [SMALL_STATE(17)] = 353,
  [SMALL_STATE(18)] = 374,
  [SMALL_STATE(19)] = 387,
  [SMALL_STATE(20)] = 400,
  [SMALL_STATE(21)] = 413,
  [SMALL_STATE(22)] = 426,
  [SMALL_STATE(23)] = 439,
  [SMALL_STATE(24)] = 452,
  [SMALL_STATE(25)] = 465,
  [SMALL_STATE(26)] = 478,
  [SMALL_STATE(27)] = 491,
  [SMALL_STATE(28)] = 514,
  [SMALL_STATE(29)] = 536,
  [SMALL_STATE(30)] = 558,
  [SMALL_STATE(31)] = 574,
  [SMALL_STATE(32)] = 585,
  [SMALL_STATE(33)] = 596,
  [SMALL_STATE(34)] = 607,
  [SMALL_STATE(35)] = 618,
  [SMALL_STATE(36)] = 629,
  [SMALL_STATE(37)] = 640,
  [SMALL_STATE(38)] = 649,
  [SMALL_STATE(39)] = 658,
  [SMALL_STATE(40)] = 671,
  [SMALL_STATE(41)] = 684,
  [SMALL_STATE(42)] = 697,
  [SMALL_STATE(43)] = 705,
  [SMALL_STATE(44)] = 715,
  [SMALL_STATE(45)] = 725,
  [SMALL_STATE(46)] = 735,
  [SMALL_STATE(47)] = 740,
  [SMALL_STATE(48)] = 745,
  [SMALL_STATE(49)] = 749,
  [SMALL_STATE(50)] = 753,
  [SMALL_STATE(51)] = 757,
  [SMALL_STATE(52)] = 761,
  [SMALL_STATE(53)] = 765,
  [SMALL_STATE(54)] = 769,
  [SMALL_STATE(55)] = 773,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 1),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 1),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 3),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global_variable_modifiers, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_global_variable_modifiers_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_global_variable_modifiers_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global_variable_declaration, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global_variable_declaration, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dimension, 3, 0, 8),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dimension, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 10),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char_literal, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 5, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_global_variable_declaration_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_variable_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 6),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 7),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 4, 0, 9),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 2, 0, 5),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global_variable_declaration, 4, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_definition, 2, 0, 4),
  [166] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_type, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_amxxpawn(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "amxxpawn",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
